/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GamingPcsRouteImport } from './routes/gaming-pcs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as ManagementPricingRouteImport } from './routes/management/pricing'
import { Route as ManagementLayoutRouteImport } from './routes/management/_layout'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingPcsRoute = GamingPcsRouteImport.update({
  id: '/gaming-pcs',
  path: '/gaming-pcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPricingRoute = ManagementPricingRouteImport.update({
  id: '/management/pricing',
  path: '/management/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementLayoutRoute = ManagementLayoutRouteImport.update({
  id: '/management/_layout',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/gaming-pcs': typeof GamingPcsRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/management': typeof ManagementLayoutRoute
  '/management/pricing': typeof ManagementPricingRoute
  '/management/': typeof ManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/gaming-pcs': typeof GamingPcsRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/management': typeof ManagementIndexRoute
  '/management/pricing': typeof ManagementPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/gaming-pcs': typeof GamingPcsRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/management/_layout': typeof ManagementLayoutRoute
  '/management/pricing': typeof ManagementPricingRoute
  '/management/': typeof ManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/gaming-pcs'
    | '/logs'
    | '/reports'
    | '/sessions'
    | '/management'
    | '/management/pricing'
    | '/management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/gaming-pcs'
    | '/logs'
    | '/reports'
    | '/sessions'
    | '/management'
    | '/management/pricing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/gaming-pcs'
    | '/logs'
    | '/reports'
    | '/sessions'
    | '/management/_layout'
    | '/management/pricing'
    | '/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  GamingPcsRoute: typeof GamingPcsRoute
  LogsRoute: typeof LogsRoute
  ReportsRoute: typeof ReportsRoute
  SessionsRoute: typeof SessionsRoute
  ManagementLayoutRoute: typeof ManagementLayoutRoute
  ManagementPricingRoute: typeof ManagementPricingRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming-pcs': {
      id: '/gaming-pcs'
      path: '/gaming-pcs'
      fullPath: '/gaming-pcs'
      preLoaderRoute: typeof GamingPcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/pricing': {
      id: '/management/pricing'
      path: '/management/pricing'
      fullPath: '/management/pricing'
      preLoaderRoute: typeof ManagementPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/_layout': {
      id: '/management/_layout'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  GamingPcsRoute: GamingPcsRoute,
  LogsRoute: LogsRoute,
  ReportsRoute: ReportsRoute,
  SessionsRoute: SessionsRoute,
  ManagementLayoutRoute: ManagementLayoutRoute,
  ManagementPricingRoute: ManagementPricingRoute,
  ManagementIndexRoute: ManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
